// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjH6kNaWDCrRlQwT6pZAEWYoM3vkvJ7I8',
    appId: '1:650426616015:web:79411126f59e4b575acfba',
    messagingSenderId: '650426616015',
    projectId: 'uptime-2f923',
    authDomain: 'uptime-2f923.firebaseapp.com',
    storageBucket: 'uptime-2f923.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgk6md1zijBEXJB8L09I9yA1T4lm_cjl0',
    appId: '1:650426616015:android:9f5f3606e8cca31e5acfba',
    messagingSenderId: '650426616015',
    projectId: 'uptime-2f923',
    storageBucket: 'uptime-2f923.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD51qR4c5DDS0MjGJ6-WMTE3mnfScXNai8',
    appId: '1:650426616015:ios:627e17e0875b26de5acfba',
    messagingSenderId: '650426616015',
    projectId: 'uptime-2f923',
    storageBucket: 'uptime-2f923.firebasestorage.app',
    iosBundleId: 'com.example.uptime',
  );
}
